### ISSUE TITLE
template v2.2.0 does not have a package available for your current platform, darwin_arm64

### ISSUE THREAD

**Issue by flypolarbear** [Young-ook/terraform-aws-eks#170]
when i use the template of [Amazon EKS on AWS Fargate](https://github.com/Young-ook/terraform-aws-eks/blob/main/examples/fargate) ,  Encountered this error while executing terroform init
![image](https://user-images.githubusercontent.com/49713432/178180996-5e8ba28c-59f6-460f-a2b2-b65b18fcdcce.png)

**Comment by mercuriete** [comment]
@flypolarbear 
That is because you are using mac M1 or a non x86 platform.
I have that problem on my organization and you can change your laptop as a workaround.

I recomend you to use a continuous integration system like github actions and the problem will be solved because github actions uses x86 virtual machines.
